# Your Name or Company
title: Paulina Rebolledo

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: Una pequeña vista previa de mi vida social y escolar, bienvenidos/as.

# Add your social links
social:
  - platform: github
    url: https://github.com/paulinarebolledo
  - platform: instagram
    url: https://www.instagram.com/rebolledopaulina_/
  - platform: spotify
    url: https://open.spotify.com/user/paulina_rebolledo1?si=366e4ccbe0bd4212
  - platform: linkedin
    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
